

version: '3.8'
services:
  go:
    container_name: go
    build: 
      context: ./infrastructure/go
      dockerfile: dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./infrastructure/mysql/.env
    depends_on:
      - db
    volumes:
      - ./backend:/go/src
      - ./infrastructure/mysql/.env:/go/src/.env

  db:
    container_name: db
    build:
      context: ./infrastructure/mysql
      dockerfile: dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./infrastructure/mysql/.env
    volumes:
      - ./infrastructure/mysql/db:/var/lib/mysql
